### ISSUE TITLE
About the function 'compute_psnr'

### ISSUE THREAD

**Issue by fkmajiji** [boazarad/NTIRE2022_spectral#3]
The original code is "10 * np.log10((peak ^ 2) / mse), mse", it uses the symbol "^" to realize the square operation, but Actually, "^" in Python is Bitwise XOR, not the square. If we set the peak value as 1, this error will make the PSNR about 4.7dB higher. The real square operation should be "**".

**Comment by boazarad** [comment]
Thanks for the find, CodaLab will be updated shortly
